on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Build "T2-Kali-Kernel"
        id: hello
        uses: rodrigoluglio/T2-Kali-Kernel@v1
